-- Create Sales table
create table public.sales (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete cascade not null,
  morning_sales numeric default 0 not null,
  evening_sales numeric default 0 not null,
  entry_date date default current_date not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, entry_date)
);

alter table public.sales enable row level security;

-- RLS Policies for Sales
create policy "Users can view their own sales" on public.sales
  for select using (user_id = auth.uid());

create policy "Users can insert their own sales" on public.sales
  for insert with check (user_id = auth.uid());

create policy "Users can update their own sales" on public.sales
  for update using (user_id = auth.uid());

create policy "Users can delete their own sales" on public.sales
  for delete using (user_id = auth.uid());
