-- Enable RLS
alter table if exists public.users enable row level security;
alter table if exists public.categories enable row level security;
alter table if exists public.expenses enable row level security;

-- Create Users table (Public profile sync with auth.users)
create table public.users (
  id uuid references auth.users on delete cascade primary key,
  username text unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.users enable row level security;

-- Create Categories table
create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  color text not null,
  is_default boolean default false not null,
  user_id uuid references public.users(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.categories enable row level security;

-- Create Expenses table
create table public.expenses (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete cascade not null,
  category_id bigint references public.categories(id) on delete set null,
  title text not null,
  amount numeric not null,
  payment_mode text not null,
  expense_date date not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.expenses enable row level security;

-- RLS Policies for Users
create policy "Users can view their own profile" on public.users
  for select using (auth.uid() = id);

create policy "Users can update their own profile" on public.users
  for update using (auth.uid() = id);

-- RLS Policies for Categories
create policy "Users can view default or their own categories" on public.categories
  for select using (is_default = true or user_id = auth.uid());

create policy "Users can insert their own categories" on public.categories
  for insert with check (user_id = auth.uid() and is_default = false);

create policy "Users can update their own categories" on public.categories
  for update using (user_id = auth.uid());

create policy "Users can delete their own categories" on public.categories
  for delete using (user_id = auth.uid());

-- RLS Policies for Expenses
create policy "Users can view their own expenses" on public.expenses
  for select using (user_id = auth.uid());

create policy "Users can insert their own expenses" on public.expenses
  for insert with check (user_id = auth.uid());

create policy "Users can update their own expenses" on public.expenses
  for update using (user_id = auth.uid());

create policy "Users can delete their own expenses" on public.expenses
  for delete using (user_id = auth.uid());

-- Trigger to sync auth.users with public.users
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, username)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1))
  );
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Seed default categories
insert into public.categories (name, color, is_default, user_id) values
('Food', '#FF7043', true, null),
('Fuel', '#26A69A', true, null),
('Travel', '#42A5F5', true, null),
('Shopping', '#AB47BC', true, null),
('Medical', '#EC407A', true, null),
('Bills', '#78909C', true, null),
('Office', '#5C6BC0', true, null),
('Entertainment', '#FFA726', true, null),
('Other', '#90A4AE', true, null);
